### Get all userinfo
GET https://project3and4.onrender.com/userinfo

### Get contact by id
GET https://project3and4.onrender.com/userinfo/6554ed54fc40da38ab849580


### Create contact
POST http://localhost:3001/userinfo HTTP/1.1
content-type: application/json

{
  "name":"Rosa",
  "username":"test6@",
  "phone":"12345698"
}


### PUT contact
PUT http://localhost:3001/userinfo/655640bb33a02a298ce7058b HTTP/1.1
content-type: application/json

{
  "name": "Juana",
  "username": "test5@",
  "phone": "12345678"
}
### DELETE contact



DELETE http://localhost:3001/userinfo/6554ed54fc40da38ab849580 HTTP/1.1